numero1=float(input("primer número: "))
numero2=float(input("segundo número: "))
print("suma")
print(numero1 + numero2)
print("resta")
print(numero1 - numero2)
print("multiplicación")
print(numero1 * numero2)
print("división")
print(numero1 / numero2)
print("módulo")
print(numero1 % numero2)
print("exponente")
print(numero1 ** numero2)
